### ISSUE TITLE
[0.0.12] Hopper extraction from fossil excavator does not work

### ISSUE THREAD

**Issue by Llight10101** [KangaliaV/Project-Dinosaur#11]
**Minecraft Version:** 1.16.5
**Mod Version:** 0.0.12
**Forge Version:** 1.16.5-36.2.39
**Dependencies & Their Versions:**
-N/A

**Expected Behaviour:** Hoppers underneath the fossil excavator removes only the result items.
**Actual Behaviour:** Hoppers underneath the fossil excavator remove _all_ items from all slots, not just the results.

**Details:**
Currently hoppers do not distinguish between input and output slots, and therefore remove all items from the machine.

**Comment by KangaliaV** [comment]
Fixed in beta version 0.6.2 (1.18.2) in commit [33e39ae](https://github.com/KangaliaV/Project-Dinosaur/commit/33e39ae813618eff9d9589fc113a18415c5610e1)
